export const SET_TOPICOS = "SET_TOPICOS"
export const SET_MATERIAS = "SET_MATERIAS"

export const FETCH_TOPICOS_FAILED = "FETCH_TOPICOS_FAILED"
export const FETCH_MATERIAS_FAILED = "FETCH_MATERIAS_FAILED"

export const SET_ACTIVE_TOPICO = "SET_ACTIVE_TOPICO"
export const SET_ACTIVE_MATERIA = "SET_ACTIVE_MATERIA"

export const RESET_ACTIVE_TOPICO = "RESET_ACTIVE_TOPICO"
export const RESET_ACTIVE_MATERIA = "RESET_ACTIVE_MATERIA"

export const REST_TOPIC = "REST_TOPIC"